### ISSUE TITLE
Ordering of leaderboard

### ISSUE THREAD

**Issue by ilundberg** [fragilefamilieschallenge/codalab-competitions#9]
The default leaderboard in Codalab assigns higher ranks to higher scores (so that the highest score is given rank 1). I think we would like to reverse this; our scores are mean squared error, so the best submission should be the one with the lowest score. Is this possible to change?

**Comment by ckcollab** [comment]
Yeah, you should be able to change this in the competition form:

![image](https://cloud.githubusercontent.com/assets/2185159/22674370/869ead00-ec94-11e6-850c-995b4105e755.png)


Or in the yaml file by specifying `sort: asc` -- just added [this example](https://github.com/codalab/codalab-competitions/wiki/User_Building-a-Competition-Bundle) to the wiki.

```
    # Actual scores in the leaderboard
    columns:
        # The internal key for this score
        DIFFERENCE:
            # This is a member of the results group
            leaderboard: *RESULTS
            # The column label for this score
            label: Difference
            # Order of the scores
            rank: 1
            # Sorting ascending instead of descending
            sort: asc
```
